swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: List of a user's accounts based on user ID
      description: An API that retrieves a list of a user's accounts based on their user ID and allows them to be displayed on their profile.
      produces:
        - application/json
      responses:
        '200':
          description: account List Recovery Completed Successfully
          schema:
            $ref: '#/definitions/AccountsList'
        '400':
          description: Failed to recover a list of accounts
        '401' :
          description: Unauthenticated User
        '404' :
          description: No accounts to display, content not found
        '500':
          description: Internal Server Error
  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions List
      description: API that retrieves the current month's transactions based on the bank account id
      parameters :
        - name : accountId
          in: path
          description : ID of the clicked account from which to retrieve the last transactions
          required : true
          type : string
        - name : month
          in : query
          description : The month of the transactions to filter, if not specified, use the current month. Input limited to a number between 1 and 12.
          required : false
          type : integer 
          minimum : 1
          maximum : 12
        - name: year
          in: query
          description: The year of the transactions to filter, if not specified, use the current year. Entry limited to a number of 4 digits, which must be less than the current year.
          required: false
          type: integer
          pattern : '^\d{4}$'
          maximum : 2025 # donnée à mettre a jour chaque année. Si possible, faire en sorte qu'il soit actualisé automatiquement.
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved the list of transactions
          schema:
            $ref: '#/definitions/TransactionList'
        '400':                                                                            
          description: Failed to recover transactions
        '401' :
          description: Unauthenticated User
        '404' :
          description: No transactions to display, content not found
        '500':
          description: Internal Server Error
  /accounts/transactions/{transactionId}:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Change category and note
      description: Api that allows you to modify the 'note' and 'category' elements on a particular transaction thanks to its ID.
      parameters:
        - name: transactionId
          in: path
          description: ID of the clicked transaction to update
          required: true
          type : string
        - name : newData
          in : body
          description: object containing newCategory and newComment
          required: true
          schema:
            $ref: '#/definitions/NewData'
      produces:
         - application/json
      responses:
        '200':
          description: Successfully Modified Datas
          schema:
            $ref: '#/definitions/DataResponse'
        '400':
          description: Data update failed
        '401' :
          description: Unauthenticated User
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AccountsList :
    type : array
    items :
      $ref: '#/definitions/Account'
  Account :
    type : object
    properties : 
      accountId : 
        type : string
        description : account number
      accountName :
        type : string
        description : account name
      sold :
        type : integer
        description : actual balance for account
  TransactionList :
      type : array
      items :
        $ref: '#/definitions/Transaction'
  Transaction :
    type : object
    properties :
      id : 
        type : string
        description : id of this transaction
      date :
        type : string
        description : date of the transaction
      description :
        type : string
        description : description of the transaction
      amount :
        type : integer
        description : amount of the transaction
      balance :
        type : integer
        description : balance after transaction
      type :
        type : string
        description : Payment Method
      category :
        type : string
        description : Expense Category
      note :
        type : string
        description : personal note of user
  NewData :
    properties :
      category :
        type : string
        description : new category selected by user
      note :
        type : string
        description : new comment wroten by user
  DataResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          category:
            description: New category selected by user
            type: string
          note:
            description : New comment added by user
            type: string
