swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Accounts List
      description: API to retrieve a user's list of accounts
      produces:
        - application/json
      responses:
        '200':
          description: account List Recovery Completed Successfully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions List
      description: API to retrieve the list of transactions from the account according to accountId
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved the list of transactions
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /categories:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Change category
      description: API to change the category of a transaction
      parameters:
        - in: body
          name: body
          description: new category Payload
          required: true
          schema:
            $ref: '#/definitions/NewCategory'
      #produces:
        # - application/json
      responses:
        '200':
          description: Successfully Modified Transaction Category
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /notes:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Change notes on transaction
      description: API to change the personal note of a transaction
      parameters:
        - in: body
          name: body
          description: new comment Payload
          required: true
          schema:
            $ref: '#/definitions/NewComment'
      #produces:
        # - application/json
      responses:
        '200':
          description: Successfully Modified Transaction Note
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Accounts :
    type : object
    properties : 
      accountId : 
        type : string
        description : account number
      accountName :
        type : string
        description : account entitled
      sold :
        type : integer
      description : actual balance for account
  Transactions :
    type : object
    Properties :
      date :
        type : string
        description : date of the transaction
      description :
        type : string
        description : description of the transaction
      amount :
        type : integer
        description : amount of the transaction
      balance :
        type : integer
        description : balance after transaction
      type :
        type : string
        description : Payment Method
      category :
        type : string
        description : Expense Category
      note :
        type : string
        description : personal note of user
  NewCategory :
    properties :
      category :
        type : string
  NewComment :
    properties :
      note :
        type : string

